export enum CargoStatus {
  ALMACENADO = "almacenado",
  EN_REVISION = "en_revision",
  LIBERADO = "liberado",
  EN_TRANSITO = "en_transito",
  DEVOLUCION = "devolucion",
  REINGRESO = "reingreso",
  RECHAZADO = "rechazado",
  CORRECCION = "correccion",
  ENTREGADA = "entregada",
  TRASNFERENCIA = "trasnferencia",
  DANIADO = "daniado",
  RETENIDO = "retenido",
  EN_ESPERA = "en_espera",
  PREPARANDO_ENTREGA = "preparando_entrega",
  EXTRAVIADO = "extraviado",
  EN_AUDITORIA = "en_auditoria",
  NO_CONFORME = "no_conforme",
}
